package edu.utfpr.cliente.ultrassom.view;

import edu.utfpr.cliente.ultrassom.view.session.Session;

public class MainScreen extends javax.swing.JFrame {

    /** Creates new form MainScreen */
    public MainScreen() {
        initComponents();
        labelHeader.setText("Bem Vindo, " + Session.getNome());
        this.setSize(805,455);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        panelBackgroundUpload = new javax.swing.JPanel();
        labelUpload = new javax.swing.JLabel();
        panelBackgroundDownload = new javax.swing.JPanel();
        labelDownload = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        panelUpload = new javax.swing.JPanel();
        labelUploadTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setBackground(new java.awt.Color(0, 51, 153));
        panelDashboard.setForeground(new java.awt.Color(0, 102, 204));

        labelUpload.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelUpload.setText("Upload");

        org.jdesktop.layout.GroupLayout panelBackgroundUploadLayout = new org.jdesktop.layout.GroupLayout(panelBackgroundUpload);
        panelBackgroundUpload.setLayout(panelBackgroundUploadLayout);
        panelBackgroundUploadLayout.setHorizontalGroup(
            panelBackgroundUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundUploadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelUpload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundUploadLayout.setVerticalGroup(
            panelBackgroundUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundUploadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelUpload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelDownload.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDownload.setText("Download");

        org.jdesktop.layout.GroupLayout panelBackgroundDownloadLayout = new org.jdesktop.layout.GroupLayout(panelBackgroundDownload);
        panelBackgroundDownload.setLayout(panelBackgroundDownloadLayout);
        panelBackgroundDownloadLayout.setHorizontalGroup(
            panelBackgroundDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelDownload)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelBackgroundDownloadLayout.setVerticalGroup(
            panelBackgroundDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelDownload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelDashboardLayout = new org.jdesktop.layout.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownload, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelBackgroundUpload, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDashboardLayout.createSequentialGroup()
                .add(103, 103, 103)
                .add(panelBackgroundUpload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(panelBackgroundDownload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        getContentPane().add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 450));

        panelHeader.setBackground(new java.awt.Color(0, 102, 204));

        labelHeader.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHeader.setText("Bem Vindo, Teste");

        org.jdesktop.layout.GroupLayout panelHeaderLayout = new org.jdesktop.layout.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 60));

        panelUpload.setBackground(new java.awt.Color(204, 204, 204));

        labelUploadTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelUploadTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUploadTitle.setText("<html><p style=\"text-align:center\">Arraste um arquivo TXT para a area abaixo<br> ou clique para selecionar o arquivo!</p></html>");

        org.jdesktop.layout.GroupLayout panelUploadLayout = new org.jdesktop.layout.GroupLayout(panelUpload);
        panelUpload.setLayout(panelUploadLayout);
        panelUploadLayout.setHorizontalGroup(
            panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelUploadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelUploadTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelUploadLayout.setVerticalGroup(
            panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelUploadLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(labelUploadTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getContentPane().add(panelUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDownload;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelUpload;
    private javax.swing.JLabel labelUploadTitle;
    private javax.swing.JPanel panelBackgroundDownload;
    private javax.swing.JPanel panelBackgroundUpload;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelUpload;
    // End of variables declaration//GEN-END:variables

}
