package edu.utfpr.cliente.ultrassom.view;

import edu.utfpr.cliente.ultrassom.view.session.Session;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileSystemView;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class MainScreen extends javax.swing.JFrame {

    /** Creates new form MainScreen */
    public MainScreen() {
        initComponents();
        labelHeader.setText("Bem Vindo, " + Session.getNome());
        this.setSize(805,455);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        textFieldUploadFile.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAlgorithm = new javax.swing.ButtonGroup();
        panelDashboard = new javax.swing.JPanel();
        panelBackgroundUpload = new javax.swing.JPanel();
        labelUpload = new javax.swing.JLabel();
        panelBackgroundDownload = new javax.swing.JPanel();
        labelDownload = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        panelUpload = new javax.swing.JPanel();
        labelUploadTitle = new javax.swing.JLabel();
        buttonFileChoose = new javax.swing.JButton();
        textFieldUploadFile = new javax.swing.JTextField();
        buttonSendFile = new javax.swing.JButton();
        radioCGNE = new javax.swing.JRadioButton();
        radioFISTA = new javax.swing.JRadioButton();
        labelAlgoritmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setBackground(new java.awt.Color(0, 51, 153));
        panelDashboard.setForeground(new java.awt.Color(0, 102, 204));

        labelUpload.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelUpload.setText("Upload");

        org.jdesktop.layout.GroupLayout panelBackgroundUploadLayout = new org.jdesktop.layout.GroupLayout(panelBackgroundUpload);
        panelBackgroundUpload.setLayout(panelBackgroundUploadLayout);
        panelBackgroundUploadLayout.setHorizontalGroup(
            panelBackgroundUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundUploadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelUpload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundUploadLayout.setVerticalGroup(
            panelBackgroundUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundUploadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelUpload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelDownload.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDownload.setText("Download");

        org.jdesktop.layout.GroupLayout panelBackgroundDownloadLayout = new org.jdesktop.layout.GroupLayout(panelBackgroundDownload);
        panelBackgroundDownload.setLayout(panelBackgroundDownloadLayout);
        panelBackgroundDownloadLayout.setHorizontalGroup(
            panelBackgroundDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelDownload)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelBackgroundDownloadLayout.setVerticalGroup(
            panelBackgroundDownloadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelDownload)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelDashboardLayout = new org.jdesktop.layout.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBackgroundDownload, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelBackgroundUpload, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDashboardLayout.createSequentialGroup()
                .add(103, 103, 103)
                .add(panelBackgroundUpload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(panelBackgroundDownload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        getContentPane().add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 450));

        panelHeader.setBackground(new java.awt.Color(0, 102, 204));

        labelHeader.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHeader.setText("Bem Vindo, Teste");

        org.jdesktop.layout.GroupLayout panelHeaderLayout = new org.jdesktop.layout.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 60));

        panelUpload.setBackground(new java.awt.Color(204, 204, 204));

        labelUploadTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelUploadTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUploadTitle.setText("Escolha um arquivo de texto para enviar para o servidor");

        buttonFileChoose.setText("Escolher arquivo...");
        buttonFileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileChooseActionPerformed(evt);
            }
        });

        textFieldUploadFile.setText("Escolha um arquivo...");

        buttonSendFile.setText("ENVIAR");
        buttonSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendFileActionPerformed(evt);
            }
        });

        buttonGroupAlgorithm.add(radioCGNE);
        radioCGNE.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        radioCGNE.setSelected(true);
        radioCGNE.setText("CGNE");

        buttonGroupAlgorithm.add(radioFISTA);
        radioFISTA.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        radioFISTA.setText("Fast Iterative Shrinkage-Thresholding Algorithm");

        labelAlgoritmo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelAlgoritmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAlgoritmo.setText("Qual algoritmo quer usar?");

        org.jdesktop.layout.GroupLayout panelUploadLayout = new org.jdesktop.layout.GroupLayout(panelUpload);
        panelUpload.setLayout(panelUploadLayout);
        panelUploadLayout.setHorizontalGroup(
            panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelUploadLayout.createSequentialGroup()
                .add(panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panelUploadLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(labelUploadTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panelUploadLayout.createSequentialGroup()
                        .add(panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, panelUploadLayout.createSequentialGroup()
                                .add(192, 192, 192)
                                .add(radioCGNE)
                                .add(18, 18, 18)
                                .add(radioFISTA))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, panelUploadLayout.createSequentialGroup()
                                .add(113, 113, 113)
                                .add(textFieldUploadFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(buttonFileChoose)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, labelAlgoritmo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(panelUploadLayout.createSequentialGroup()
                .add(241, 241, 241)
                .add(buttonSendFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUploadLayout.setVerticalGroup(
            panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelUploadLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(labelUploadTitle)
                .add(43, 43, 43)
                .add(panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonFileChoose)
                    .add(textFieldUploadFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(labelAlgoritmo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(panelUploadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioCGNE)
                    .add(radioFISTA))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(buttonSendFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35))
        );

        getContentPane().add(panelUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileChooseActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                textFieldUploadFile.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_buttonFileChooseActionPerformed

    private void buttonSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendFileActionPerformed
        try {
            BufferedReader br = new BufferedReader(new FileReader(textFieldUploadFile.getText()));
            JSONArray data = new JSONArray();
            for(int j = 0; j < 64; j++){
                for(int i = 0; i < 794; i++){
                    double g = Double.parseDouble(br.readLine());
                    double gama = 100+(1/20*i*Math.sqrt(i));
                    g = g*gama;
                    data.add(g);
                }
            }
            br.close();
            URL url = new URL("http://localhost:8080/process");
            HttpURLConnection con = (HttpURLConnection)url.openConnection();
            //Declaranco método e tipo do conteúdo
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Accept", "application/json");
            //Falando que vamos enviar algo
            con.setDoOutput(true);
            con.setDoInput(true);
            
            JSONObject body = new JSONObject();
            body.put("data", data);
            body.put("usuario_id", Session.getId());
            body.put("algoritmo", radioCGNE.isSelected() ? radioCGNE.getText() : radioFISTA.getText());
            
            DataOutputStream wr = new DataOutputStream(con.getOutputStream());
            wr.writeBytes(body.toString());
            wr.flush();
            wr.close();
            
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            String response = "";
            while((inputLine = in.readLine()) != null)
                response += inputLine;
            in.close();
            JSONParser parser = new JSONParser();
            JSONObject json = (JSONObject) parser.parse(response);
            showMessageDialog(null,"Enviado com sucesso!");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSendFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFileChoose;
    private javax.swing.ButtonGroup buttonGroupAlgorithm;
    private javax.swing.JButton buttonSendFile;
    private javax.swing.JLabel labelAlgoritmo;
    private javax.swing.JLabel labelDownload;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelUpload;
    private javax.swing.JLabel labelUploadTitle;
    private javax.swing.JPanel panelBackgroundDownload;
    private javax.swing.JPanel panelBackgroundUpload;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelUpload;
    private javax.swing.JRadioButton radioCGNE;
    private javax.swing.JRadioButton radioFISTA;
    private javax.swing.JTextField textFieldUploadFile;
    // End of variables declaration//GEN-END:variables

}
